// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZd6GlDWC1gfXRi1i2hdCHW3c2Ve3kSzQ',
    appId: '1:754254352128:web:3dfb2484309ba7f11dede5',
    messagingSenderId: '754254352128',
    projectId: 'to-do-app-757fe',
    authDomain: 'to-do-app-757fe.firebaseapp.com',
    storageBucket: 'to-do-app-757fe.appspot.com',
    measurementId: 'G-CLLCPZKNZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL2jBJ3JFxXeEseU9yyU7rtOIhE2xKhFo',
    appId: '1:754254352128:android:a303d0568c86f4dc1dede5',
    messagingSenderId: '754254352128',
    projectId: 'to-do-app-757fe',
    storageBucket: 'to-do-app-757fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_d1Evy72GLR6neSNUq0FJ2G1p9ril4G4',
    appId: '1:754254352128:ios:3eef3a9e228d15c61dede5',
    messagingSenderId: '754254352128',
    projectId: 'to-do-app-757fe',
    storageBucket: 'to-do-app-757fe.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_d1Evy72GLR6neSNUq0FJ2G1p9ril4G4',
    appId: '1:754254352128:ios:993c7635a02812001dede5',
    messagingSenderId: '754254352128',
    projectId: 'to-do-app-757fe',
    storageBucket: 'to-do-app-757fe.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
